### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by foxwave88** [michaelbrusegard/WebGL-Fluid-Simulation#19]
i was using it for months but for a while (i think atleast for last week) it stopped working. New version is not working on me because i had to use old node version how cani fix

**Comment by michaelbrusegard** [comment]
Well the new version works differently and has a new API. You can either update to the new version and change the code to the new API, or you can set the package.json to use the old version (0.6.1).

**Comment by foxwave88** [comment]
I didnt update anything and  didnt change anything in my codes. But it stopped working. But if i change package.json to the 0.6.1 i guess it will work. I will try and let you know. Thank you for answer.

**Comment by michaelbrusegard** [comment]
Yea it was probably set to use the latest version in the package.json using the ^ arrow on the version number. Glad you got it working

**Comment by foxwave88** [comment]
These are my package codes, it was already0.6.1 i didnt change it.
"webgl-fluid-enhanced": "^0.6.1",

"node_modules/webgl-fluid-enhanced": {
      "version": "0.6.1",
      "resolved": "https://registry.npmjs.org/webgl-fluid-enhanced/-/webgl-fluid-enhanced-0.6.1.tgz",
      "integrity": "sha512-prZBEkNhoy+stOCUVh9WL3Zkes43h/N1q4lTWqLweACUcjBS/QOrlUZVaXWvXodHdG/6MBxdwiddx13YjForZA=="
    },
    
    
    
    <script type="module">
  import { initializeFluidSimulation } from './fluid.js';
  const settings = {
      COLOR_PALETTE: ['#FFD700'] 
    };
    initializeFluidSimulation(document.querySelector('canvas'), settings);  
</script>

and this is my fluid.js codes:

import webGLFluidEnhanced from 'https://unpkg.com/webgl-fluid-enhanced@latest';
export function initializeFluidSimulation(canvasElement, userSettings = {}) {
    const defaultSettings = {

//some configurations

 };

   
    const settings = { ...defaultSettings, ...userSettings };

    webGLFluidEnhanced.simulation(canvasElement, settings);
}


I didnt change any of codes and suddenly it stopped working. What might be the problem? my node module is already 0.6.1

**Comment by michaelbrusegard** [comment]
If it suddenly stopped working, but the version did not change then it does not have anything to do with the package being updated. Then you must have changed something in your config
